/**
 * DB 스키마.
 *
 * 파일(.sql)이 아니라 문자열 상수로 둔다.
 * Next.js 번들 환경에서는 readFileSync(new URL(...)) 이 동작하지 않아
 * 서버 컴포넌트가 스키마를 읽지 못한다(실측 확인).
 */
export type SqlDialect = "sqlite" | "postgres";

/**
 * 스키마 DDL 을 방언에 맞게 돌려준다. 정본은 아래 SQLite 문법(SCHEMA_SQL)이고,
 * Postgres 는 최소 치환만 한다:
 *   - INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 *   - 그 외 INTEGER → BIGINT (id 컬럼 32비트 오버플로 예방 겸)
 * 나머지(TEXT·REAL·DEFAULT·PRIMARY KEY(...)·ON CONFLICT·CREATE INDEX IF NOT EXISTS)는
 * 두 엔진 모두 그대로 받는다. PRAGMA 는 SCHEMA_SQL 에 없다(openDb 에서 sqlite 에만 건다).
 */
export function schemaSqlFor(dialect: SqlDialect): string {
  if (dialect === "sqlite") return SCHEMA_SQL;
  return SCHEMA_SQL
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bINTEGER\b/g, "BIGINT");
}

export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS cases (
  request_id           INTEGER PRIMARY KEY,
  request_id_formatted TEXT    NOT NULL,
  subject              TEXT    NOT NULL DEFAULT '',
  status               TEXT    NOT NULL DEFAULT '',
  priority             TEXT    NOT NULL DEFAULT '',
  category             TEXT    NOT NULL DEFAULT '',
  party_name           TEXT    NOT NULL DEFAULT '',
  party_site_number    TEXT    NOT NULL DEFAULT '',
  created_on           TEXT    NOT NULL DEFAULT '',
  created_on_ms        INTEGER,
  last_updated         TEXT    NOT NULL DEFAULT '',
  last_updated_ms      INTEGER,
  first_seen_at        TEXT    NOT NULL,
  last_fetched_at      TEXT    NOT NULL,
  raw_json             TEXT    NOT NULL DEFAULT '{}',
  -- 케이스를 최초 등록할 때 우리가 쓴 본문. 스레드가 아니라 별도 필드로 온다.
  description_html     TEXT    NOT NULL DEFAULT '',
  description_text     TEXT    NOT NULL DEFAULT '',
  -- 답변 등록 시 필요한 낙관적 잠금 값
  case_version         INTEGER,
  -- SR 작성 폼의 Product / Component. 실제로 쓰인 조합을 모으기 위해 저장한다.
  product_id           INTEGER,
  product_name         TEXT NOT NULL DEFAULT '',
  component_id         INTEGER,
  component_name       TEXT NOT NULL DEFAULT '',
  -- 팀(공용 계정) 소유. 신규 DB 는 여기서 바로 만든다(런타임 ALTER 불필요 → PG 소유권 문제 회피).
  -- 기존 SQLite DB 는 아래 ADDED_COLUMNS 마이그레이션이 채운다.
  team_id              TEXT NOT NULL DEFAULT 'default'
);

CREATE INDEX IF NOT EXISTS idx_cases_last_updated ON cases(last_updated_ms DESC);

CREATE TABLE IF NOT EXISTS threads (
  thread_id      INTEGER PRIMARY KEY,
  request_id     INTEGER NOT NULL,
  author_unit    TEXT    NOT NULL DEFAULT '',
  author_unit_id INTEGER NOT NULL DEFAULT 0,
  -- 1 = 우리가 쓴 글, 0 = 상대(Broadcom) 답변
  is_ours        INTEGER NOT NULL DEFAULT 0,
  res_date_ms    INTEGER,
  res_date_val   TEXT    NOT NULL DEFAULT '',
  body_html      TEXT    NOT NULL DEFAULT '',
  body_text      TEXT    NOT NULL DEFAULT '',
  fetched_at     TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_threads_request ON threads(request_id, res_date_ms DESC);

-- 수집 실행 이력.
-- status 를 3값으로 구분하는 것이 핵심이다.
--   success         : 정상 수집
--   session_expired : 세션이 끊겨 조회하지 못함  <- '새 답변 0건'과 절대 같지 않다
--   failed          : 그 외 실패
CREATE TABLE IF NOT EXISTS runs (
  run_id        INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at    TEXT    NOT NULL,
  finished_at   TEXT,
  status        TEXT    NOT NULL,
  cases_seen    INTEGER NOT NULL DEFAULT 0,
  cases_changed INTEGER NOT NULL DEFAULT 0,
  new_threads   INTEGER NOT NULL DEFAULT 0,
  session_state TEXT    NOT NULL DEFAULT '',
  error         TEXT
);

CREATE INDEX IF NOT EXISTS idx_runs_started ON runs(started_at DESC);

-- 팀이 어디까지 확인했는지. 계정을 공유하므로 팀 단위 읽음 상태로 둔다.
-- last_read_thread_ms 보다 새로운 상대 답변이 있으면 '새 답변'이다.
-- NVD 에서 가져온 보안 취약점.
-- 우리가 지원하는 제품 키워드로 조회한 결과이며, 키워드 매칭이라 무관한 것이 섞일 수 있다.
-- dismissed = 1 이면 화면에서 숨긴다(관련 없다고 판단한 것).
CREATE TABLE IF NOT EXISTS cves (
  cve_id     TEXT NOT NULL,
  product    TEXT NOT NULL,
  keyword    TEXT NOT NULL DEFAULT '',
  severity   TEXT NOT NULL DEFAULT '',
  score      REAL,
  published  TEXT NOT NULL DEFAULT '',
  modified   TEXT NOT NULL DEFAULT '',
  summary    TEXT NOT NULL DEFAULT '',
  url        TEXT NOT NULL DEFAULT '',
  fetched_at TEXT NOT NULL,
  first_seen TEXT NOT NULL,
  dismissed  INTEGER NOT NULL DEFAULT 0,
  vector              TEXT NOT NULL DEFAULT '',
  attack_vector       TEXT NOT NULL DEFAULT '',
  attack_complexity   TEXT NOT NULL DEFAULT '',
  privileges_required TEXT NOT NULL DEFAULT '',
  user_interaction    TEXT NOT NULL DEFAULT '',
  impact_c            TEXT NOT NULL DEFAULT '',
  impact_i            TEXT NOT NULL DEFAULT '',
  impact_a            TEXT NOT NULL DEFAULT '',
  cwe                 TEXT NOT NULL DEFAULT '',
  references_json     TEXT NOT NULL DEFAULT '[]',
  affected_json       TEXT NOT NULL DEFAULT '[]',
  -- 한국어 번역. 한 번 만들면 다시 부르지 않는다.
  summary_ko          TEXT NOT NULL DEFAULT '',
  -- 담당자용 3줄 정리 (무엇이 / 영향 / 확인할 것)
  brief_ko            TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (cve_id, product)
);

CREATE INDEX IF NOT EXISTS idx_cves_published ON cves(published DESC);

-- 케이스 첨부파일.
-- 파일 실체는 Broadcom 쪽(supportftp)에 있고 우리는 목록과 링크만 갖는다.
-- 204MB 짜리도 있어서 내려받아 보관하지 않는다.
CREATE TABLE IF NOT EXISTS attachments (
  document_id  INTEGER PRIMARY KEY,
  request_id   INTEGER NOT NULL,
  thread_id    INTEGER,
  doc_name     TEXT    NOT NULL DEFAULT '',
  doc_path     TEXT    NOT NULL DEFAULT '',
  content_type TEXT    NOT NULL DEFAULT '',
  file_size    INTEGER NOT NULL DEFAULT 0,
  uploaded_by  TEXT    NOT NULL DEFAULT '',
  uploaded_at  TEXT    NOT NULL DEFAULT '',
  uploaded_ms  INTEGER,
  fetched_at   TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_attachments_request ON attachments(request_id, uploaded_ms DESC);

-- 종료 케이스 정리 결과.
-- 처음 요청할 때 만들어 저장하고, 이후에는 저장분을 그대로 돌려준다.
-- source: draft = 수집 데이터로 엮은 초안, ai = AI 로 다듬은 것
CREATE TABLE IF NOT EXISTS case_summaries (
  request_id   INTEGER NOT NULL,
  kind         TEXT    NOT NULL,
  content      TEXT    NOT NULL,
  source       TEXT    NOT NULL DEFAULT 'draft',
  generated_at TEXT    NOT NULL,
  PRIMARY KEY (request_id, kind)
);

CREATE TABLE IF NOT EXISTS case_reads (
  request_id          INTEGER PRIMARY KEY,
  last_read_thread_ms INTEGER NOT NULL DEFAULT 0,
  read_at             TEXT    NOT NULL
);

-- 정기점검 보고서의 월별 인스턴스 입력값.
-- 결과(container_*)를 같이 저장하는 이유는 다음 달 "전월 대비 증감" 때문이다.
-- 이 값이 있으면 다음 달에는 입력 9개만 넣으면 된다.
-- month 는 'YYYY-MM'.
CREATE TABLE IF NOT EXISTS instance_counts (
  month                TEXT    PRIMARY KEY,
  bank_dev             REAL    NOT NULL,
  bank_prod            REAL    NOT NULL,
  bank_dr              REAL    NOT NULL,
  central_dev          REAL    NOT NULL,
  central_prod         REAL    NOT NULL,
  central_dr           REAL    NOT NULL,
  shared_dev           REAL    NOT NULL,
  shared_prod          REAL    NOT NULL,
  shared_dr            REAL    NOT NULL,
  container_bank_prod         REAL NOT NULL,
  container_bank_prod_shared  REAL NOT NULL,
  container_bank_dev          REAL NOT NULL,
  container_bank_dev_shared   REAL NOT NULL,
  container_central_prod      REAL NOT NULL,
  container_central_dev       REAL NOT NULL,
  -- 이 달을 계산할 때 실제로 쓴 전월값.
  -- 앞선 달이 저장돼 있으면 그 값이 들어가고, 첫 달이면 사람이 넣은 값이 들어간다.
  -- 남겨두면 "무엇과 비교한 증감인지"를 나중에도 알 수 있다.
  prev_bank_prod         REAL NOT NULL DEFAULT 0,
  prev_bank_prod_shared  REAL NOT NULL DEFAULT 0,
  prev_bank_dev          REAL NOT NULL DEFAULT 0,
  prev_bank_dev_shared   REAL NOT NULL DEFAULT 0,
  prev_central_prod      REAL NOT NULL DEFAULT 0,
  prev_central_dev       REAL NOT NULL DEFAULT 0,
  saved_at             TEXT    NOT NULL
);

-- 정기점검 보고서에 넣기로 고른 항목들.
-- kind: 'sr' = 케이스 번호, 'jira' = 이슈 키.
-- 단계를 옮겨다녀도 선택이 남아야 해서 저장한다.
CREATE TABLE IF NOT EXISTS report_picks (
  month TEXT    NOT NULL,
  kind  TEXT    NOT NULL,
  ref   TEXT    NOT NULL,
  ord   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (month, kind, ref)
);

-- 팀 = 공용 브로드컴 계정 단위.
-- 한 팀이 계정 하나를 공유한다. 다른 팀이 들어오면 자기 팀 계정을 쓴다.
-- 세션·기기신뢰는 계정에 묶이므로 팀마다 각각(팀 안에서는 하나를 공유).
-- broadcom_username 은 어느 공용 계정인지 식별용 라벨. 비밀번호는 여기 넣지 않는다.
CREATE TABLE IF NOT EXISTS teams (
  team_id           TEXT PRIMARY KEY,
  team_name         TEXT NOT NULL DEFAULT '',
  broadcom_username TEXT NOT NULL DEFAULT '',
  created_at        TEXT NOT NULL
);

-- 감사 로그.
-- 쓰기(작성/답변)는 공용 계정으로 나가지만, 우리 서비스 사용자 중 누가 시켰는지 남긴다.
-- actor 는 챗봇이 넘긴 요청 사용자 식별자(사번/이메일 등, 합의 필요).
-- result: 'ok' 또는 'failed:<code>'.
CREATE TABLE IF NOT EXISTS audit_log (
  log_id      INTEGER PRIMARY KEY AUTOINCREMENT,
  at          TEXT    NOT NULL,
  actor       TEXT    NOT NULL DEFAULT '',
  team_id     TEXT    NOT NULL DEFAULT '',
  action      TEXT    NOT NULL,
  request_id  INTEGER,
  result      TEXT    NOT NULL DEFAULT '',
  detail      TEXT    NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_audit_at ON audit_log(at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_team ON audit_log(team_id, at DESC);

-- 팀별 MCP 접속 토큰.
-- token_hash 는 평문 토큰의 SHA-256 해시(hex)다. 평문 토큰은 어디에도 저장하지 않는다
-- (발급 시 호출자에게 딱 한 번 반환할 뿐이다).
-- revoked = 1 이면 검증에서 거부한다. 삭제하지 않고 이력으로 남긴다.
CREATE TABLE IF NOT EXISTS team_tokens (
  token_hash   TEXT PRIMARY KEY,
  team_id      TEXT NOT NULL,
  label        TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL,
  last_used_at TEXT,
  revoked      INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_team_tokens_team ON team_tokens(team_id);

-- 팀별 외부 연동(Jira 등) 자격.
-- kind 로 연동 종류를 구분한다("jira" 등) — 앞으로 다른 연동도 같은 틀을 쓴다.
-- secret_enc 는 토큰 등 민감값을 AES-256-GCM 으로 암호화한 것(lib/secretBox.ts).
-- 평문은 여기 절대 들어가지 않는다. 암호화 키(SR_SECRET_KEY)가 없으면 저장 자체를 거부한다.
CREATE TABLE IF NOT EXISTS team_integrations (
  team_id    TEXT NOT NULL,
  kind       TEXT NOT NULL,
  base_url   TEXT NOT NULL DEFAULT '',
  project    TEXT NOT NULL DEFAULT '',
  secret_enc TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL,
  PRIMARY KEY (team_id, kind)
);

CREATE INDEX IF NOT EXISTS idx_team_integrations_team ON team_integrations(team_id);

-- LLM 연결 설정.
-- 지금은 전역 단일 활성 연결(llm_id='default'). 앞으로 여러 개가 필요하면 id 로 늘린다.
-- 요약·리포트·답변요약이 이 설정을 읽어 OpenAI 대신 지정한 엔드포인트를 쓴다.
-- auth_kind:
--   keycloak = 호출마다 token_url 에서 액세스 토큰 발급(비밀번호 그랜트) 후 Bearer 로 사용
--   bearer   = secret_enc 를 그대로 Bearer 토큰(API 키)으로 사용
--   none     = 인증 헤더 없음
-- secret_enc 는 비밀번호(또는 API 키)를 AES-256-GCM 으로 암호화한 것(lib/secretBox.ts).
-- 평문은 여기 절대 들어가지 않는다. 키(SR_SECRET_KEY)가 없으면 저장을 거부한다.
-- 팀별 세션/기기신뢰 상태의 durable 백업.
-- session.json(Playwright storageState)·device.json(MFA 신뢰기기) 을 통째 JSON 으로 담는다.
-- TAS 파일시스템은 재시작마다 초기화되므로, 로그인/persist 때 여기로 밀어넣고(persist)
-- 컨테이너 시작·쓰기 전에 여기서 파일로 복원한다(hydrate). 파일 로직 자체는 그대로 둔다.
CREATE TABLE IF NOT EXISTS team_session_state (
  team_id      TEXT PRIMARY KEY,
  session_json TEXT NOT NULL DEFAULT '',
  device_json  TEXT NOT NULL DEFAULT '',
  updated_at   TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS llm_connections (
  llm_id        TEXT PRIMARY KEY,
  name          TEXT    NOT NULL DEFAULT '',
  model_id      TEXT    NOT NULL DEFAULT '',
  base_url      TEXT    NOT NULL DEFAULT '',
  auth_kind     TEXT    NOT NULL DEFAULT 'keycloak',
  token_url     TEXT    NOT NULL DEFAULT '',
  client_id     TEXT    NOT NULL DEFAULT '',
  auth_username TEXT    NOT NULL DEFAULT '',
  secret_enc    TEXT    NOT NULL DEFAULT '',
  chat_path     TEXT    NOT NULL DEFAULT '/v1/chat/completions',
  max_tokens    INTEGER NOT NULL DEFAULT 512,
  temperature   REAL    NOT NULL DEFAULT 0.1,
  system_prompt TEXT    NOT NULL DEFAULT '',
  updated_at    TEXT    NOT NULL DEFAULT ''
);

-- 프로세스 사이에 남겨야 하는 작은 값들(워터마크 등).
-- TAS 는 파일시스템이 ephemeral 이라 파일에 두면 재시작마다 사라진다.
CREATE TABLE IF NOT EXISTS app_state (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT ''
);
`;
